import 'dart:convert';
import 'package:http/http.dart' as http;
import 'auth_session.dart';
import 'catalog_api.dart' show defaultApiBaseUrl;

class CorporateApiException implements Exception { CorporateApiException(this.message, {this.statusCode}); final String message; final int? statusCode; @override String toString() => message; }

class CorporateApiClient {
  CorporateApiClient({http.Client? client, String? baseUrl}) : _client = client ?? http.Client(), baseUrl = (baseUrl ?? defaultApiBaseUrl).replaceFirst(RegExp(r'/$'), '');
  final http.Client _client; final String baseUrl;
  Map<String,String> get _headers { final token = OwnerSession.instance.bearerToken; if (token == null) throw CorporateApiException('نشست شما منقضی شده است.', statusCode: 401); return {'authorization':'Bearer $token'}; }
  Future<List<CorporateRequestSummary>> fetchRequests({String? status, String? query}) async { final params = <String,String>{if (status != null && status.isNotEmpty) 'status':status, if (query != null && query.isNotEmpty) 'query':query}; final response = await _client.get(Uri.parse('$baseUrl/api/v1/admin/corporate-requests').replace(queryParameters: params),headers:_headers); _guard(response); if(response.statusCode!=200) throw CorporateApiException(_message(response),statusCode:response.statusCode); final list=jsonDecode(utf8.decode(response.bodyBytes)) as List<dynamic>; return list.map((item)=>CorporateRequestSummary.fromJson(item as Map<String,dynamic>)).toList(); }
  Future<CorporateSummary> fetchSummary() async { final response=await _client.get(Uri.parse('$baseUrl/api/v1/admin/corporate-requests/summary'),headers:_headers); _guard(response); if(response.statusCode!=200) throw CorporateApiException(_message(response),statusCode:response.statusCode); return CorporateSummary.fromJson(jsonDecode(utf8.decode(response.bodyBytes)) as Map<String,dynamic>); }
  Future<CorporateRequestDetail> fetchDetail(String id) async { final response=await _client.get(Uri.parse('$baseUrl/api/v1/admin/corporate-requests/$id'),headers:_headers); _guard(response); if(response.statusCode!=200) throw CorporateApiException(_message(response),statusCode:response.statusCode); return CorporateRequestDetail.fromJson(jsonDecode(utf8.decode(response.bodyBytes)) as Map<String,dynamic>); }
  Future<void> changeStatus(String id,String status,{String? note}) => _send('PATCH','/api/v1/admin/corporate-requests/$id/status',{'status':status,'note':note});
  Future<void> assign(String id,String? assignedTo) => _send('POST','/api/v1/admin/corporate-requests/$id/assign',{'assignedTo':assignedTo});
  Future<void> followUp(String id,DateTime? date) => _send('POST','/api/v1/admin/corporate-requests/$id/follow-up',{'nextFollowUpAt':date?.toUtc().toIso8601String()});
  Future<void> addNote(String id,String note) => _send('POST','/api/v1/admin/corporate-requests/$id/notes',{'note':note});
  Future<void> _send(String method,String path,Map<String,dynamic> body) async { final uri=Uri.parse('$baseUrl$path'); final response=method=='PATCH'?await _client.patch(uri,headers:{..._headers,'content-type':'application/json'},body:jsonEncode(body)):await _client.post(uri,headers:{..._headers,'content-type':'application/json'},body:jsonEncode(body)); _guard(response); if(response.statusCode<200||response.statusCode>=300) throw CorporateApiException(_message(response),statusCode:response.statusCode); }
  void _guard(http.Response response){if(response.statusCode==401) {OwnerSession.instance.clear();throw CorporateApiException('نشست شما منقضی شده است؛ دوباره وارد شوید.',statusCode:401);}}
  String _message(http.Response response){try{final body=jsonDecode(utf8.decode(response.bodyBytes));if(body is Map && body['message'] is String)return body['message'] as String;}catch(_){ }return 'ارتباط با سرور با خطا مواجه شد (${response.statusCode}).';}
}

class CorporateRequestSummary { const CorporateRequestSummary({required this.id,required this.customerName,required this.companyName,required this.mobile,required this.city,required this.occasion,required this.orderQuantity,required this.packageType,required this.status,required this.assignedTo,required this.nextFollowUpAt,required this.createdAt}); final String id,customerName,companyName,mobile,city,occasion,packageType,status; final int orderQuantity; final String? assignedTo; final DateTime? nextFollowUpAt; final DateTime createdAt; factory CorporateRequestSummary.fromJson(Map<String,dynamic> j)=>CorporateRequestSummary(id:j['id'].toString(),customerName:j['customerName'] as String,companyName:j['companyName'] as String,mobile:j['mobile'] as String,city:j['city'] as String,occasion:j['occasion'] as String,orderQuantity:j['orderQuantity'] as int,packageType:j['packageType'] as String,status:j['status'] as String,assignedTo:j['assignedTo'] as String?,nextFollowUpAt:j['nextFollowUpAt']==null?null:DateTime.parse(j['nextFollowUpAt'] as String),createdAt:DateTime.parse(j['createdAt'] as String)); }
class CorporateSummary { const CorporateSummary(this.newCount,this.unfollowedCount); final int newCount,unfollowedCount; factory CorporateSummary.fromJson(Map<String,dynamic> j)=>CorporateSummary(j['newCount'] as int,j['unfollowedCount'] as int); }
class CorporateRequestDetail { const CorporateRequestDetail({required this.id,required this.customerName,required this.companyName,required this.mobile,required this.email,required this.city,required this.occasion,required this.orderQuantity,required this.packageType,required this.budget,required this.deliveryDate,required this.customPackaging,required this.description,required this.status,required this.assignedTo,required this.nextFollowUpAt,required this.internalNote,required this.createdAt}); final String id,customerName,companyName,mobile,city,occasion,packageType,status; final String? email,description,assignedTo,nextFollowUpAt,internalNote; final int orderQuantity; final num? budget; final DateTime? deliveryDate,createdAt; final bool customPackaging; factory CorporateRequestDetail.fromJson(Map<String,dynamic> j)=>CorporateRequestDetail(id:j['id'].toString(),customerName:j['customerName'] as String,companyName:j['companyName'] as String,mobile:j['mobile'] as String,email:j['email'] as String?,city:j['city'] as String,occasion:j['occasion'] as String,orderQuantity:j['orderQuantity'] as int,packageType:j['packageType'] as String,budget:j['budget'] as num?,deliveryDate:j['deliveryDate']==null?null:DateTime.parse(j['deliveryDate'] as String),customPackaging:j['customPackaging'] as bool,description:j['description'] as String?,status:j['status'] as String,assignedTo:j['assignedTo'] as String?,nextFollowUpAt:j['nextFollowUpAt'] as String?,internalNote:j['internalNote'] as String?,createdAt:DateTime.parse(j['createdAt'] as String)); }
